version: '3.1'
services:
  nesteo-db:
    image: mariadb
    container_name: nesteo-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /root/nesteo/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
  nesteo-server:
    # Change 'latest' to whatever tag you want to use: https://hub.docker.com/r/nesteo/server/tags
    image: nesteo/server:${SERVER_TAG}
    container_name: nesteo-server
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ${SERVER_CONFIG_FILE_PATH}:/app/appsettings.json
    ports:
      - "${SERVER_PORT}:80"
